### PR TITLE
Add PiP hotkey controls

### PR DESCRIPTION
**Pull request by Akhilnautiyal5**
Added controls features in main.js :
In addVideoKeyboardControls function I added the event listener to execute change like:
    - left arrow key for rewind.
    - right arrow key for forward.
    - space bar for play pause.

### CODE REVIEW

**Comment by Akhilnautiyal5** [comment]
please review the above code and let me know if there is any problem with the code.
Iam looking forward to your reply.

**Review by NotAddison — CHANGES_REQUESTED** [review]
Hey SFLR!
The code implementations looks solid, 
however if its not too much trouble, could you to add the hotkeys to the extension menu as a setting?

So rather than hard coding the key codes, 
it would be better if you let the user decide which keys they want to bind rewind, forward and pause to via the extension menu.

Also you might want to add a "hotkey" button as currently pressing space would pause / play the PiP Video which can be quite distracting if the user is typing while the PiP is playing :P.  So maybe (ALT + Space) rather than just Space.

**Comment by Akhilnautiyal5** [comment]
Just pushed updated code.
Add customizable hotkeys to extension menu:

- Implemented user-configurable keyboard shortcuts
- Updated settings storage to include hotkey preferences
- Modified event listeners to use custom hotkeys
- Updated extension menu UI to allow hotkey customization

**Review by NotAddison — APPROVED** [review]
LGTM! 
I'll do a quick test on my end and make some slight changes here and there,
I should (probably) be able to merge it into a new release latest by next week when I have some free time.

Thanks for contributing :)

**Comment by Akhilnautiyal5** [comment]
Subject: Thank You for Approving My Contribution

Hi Addison,

I hope you're doing well.

Just wanted to thank you for reviewing and merging my pull request into the
`AutoPiP` project. I'm really excited to have contributed and appreciate
the opportunity!

If you have a moment, I'd love it if you could endorse me for the skills I
used in the project on LinkedIn. Here's my profile: Akhil Nautiyal -
LinkedIn(https://www.linkedin.com/in/akhil-nautiyal-69aaaa288).

Thanks again, and I look forward to seeing the next steps for the project!

Best regards,
Akhil Nautiyal

**Comment by NotAddison** [comment]
Hey @Akhilnautiyal5,

I've just merged it to the dev branch but there seems to be some error when trying to use the hotkeys that you've implemented.
Could you check out the dev branch to see if the changes merged was correct or is working on your end?

**Pull request merged**
